### ISSUE TITLE
对不起，没看明白

### ISSUE THREAD

**Issue by lVBY** [bigxixi/Sketch2AE#5]
只弄出这个。 https://gist.github.com/lVBY/d0ae77b7c7bb72cfbc04f6ca484876f8

**Comment by bigxixi** [comment]
打开After Effect，执行 文件 -> 脚本 -> 运行脚本文件, 选择你导出的这个 .jsx 文件并点确定。这样就能导入到ae里了。

**Comment by lVBY** [comment]
谢谢:-)
