### ISSUE TITLE
Error on line: 1364 

### ISSUE THREAD

**Issue by ssibjay** [bigxixi/Sketch2AE#6]
<img width="455" alt="screen shot 2017-09-23 at 1 00 16 pm" src="https://user-images.githubusercontent.com/32225527/30775348-7e2dce10-a05f-11e7-9486-eceac8541dae.png">

Hi, 

I am having an issue with the plugin when I try to import saved files from Sketch into AE. I click on "Open layer data from sktchae file" and I get an error pop up saying "Error on line:1364"

Anyone knows how to fix this?

Thanks in advance!!

Tae

**Comment by bigxixi** [comment]
I think you are using Google's "Sketch2AE", you can visit https://google.github.io/sketch2ae/ for help.
