### ISSUE TITLE
Error on line: 1473

### ISSUE THREAD

**Issue by Frecklyy** [bigxixi/Sketch2AE#7]
Hi! Recently I couldn't freely copy/paste elements from Sketch to AE. It gives me an error: Error line 1473. After some investigation I found out that it is caused when you try to copy text layers. Does anyone have the same problem?

**Comment by bigxixi** [comment]
I am sorry but this plungin doesnt't work in 'Copy and Save' way.
Google released another 'Sketch2AE' plugin, maybe you are using that one?
https://google.github.io/sketch2ae/

**Comment by Frecklyy** [comment]
yes, I thought it was the same. thanks for the answer!
