### ISSUE TITLE
Cannot paste code or save selected layers

### ISSUE THREAD

**Issue by ssupremenyc** [bigxixi/Sketch2AE#8]
Sketch plugin doesn't seem to work with Sketch 49. Copy and Save selected layers doesn't seem to do anything?

**Comment by groenroos** [comment]
I seem to be having the same issue.

**Comment by bigxixi** [comment]
I havent update to v49 yet, but this plungin doesnt't work in 'Copy and Save' way.
Google released another 'Sketch2AE' plugin, maybe you are using that one?
https://google.github.io/sketch2ae/
